---
kind: pipeline
type: docker
name: build_image

trigger:
  event:
    cron
  cron:
    trigger_build

steps:
- name: build_arch-makepkg
  image: plugins/kaniko
  settings:
    registry: https://index.docker.io/v1/
    repo: zaggash/arch-makepkg
    tags: latest
    dockerfile: Dockerfile
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD

- name: notify_telegram
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: TELEGRAM_TOKEN
    to:
      from_secret: TELEGRAM_GROUPID
    format: markdown
    message: >
      ❌ zaggash/arch-makepkg:latest
         Image build #{{build.number}} from `{{repo.name}}` failed.
      🌐 {{ build.link }}
  when:
    status:
    - failure


