---
kind: pipeline
type: kubernetes
name: build_image

trigger:
  event:
    cron
  cron:
    trigger_build

steps:
- name: build_arch-makepkg
  image: plugins/kaniko:1.4.1
  settings:
    registry: https://index.docker.io/v1/
    repo: zaggash/arch-makepkg
    tags: latest
    dockerfile: Dockerfile
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD

- name: notify_discord
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: GLOBAL_CI_DISCORD_ID
    webhook_token:
      from_secret: GLOBAL_CI_DISCORD_TOKEN
    message: >
      ❌ zaggash/arch-makepkg:latest
         Image build #{{build.number}} from `{{repo.name}}` failed.
      🌐 {{ build.link }}
  when:
    status:
    - failure


