---
kind: pipeline
type: docker
name: build_image

trigger:
  event:
    cron
  cron:
    trigger_build

steps:
- name: trigger_dockerhub
  image: plugins/webhook
  settings:
    urls:
      from_secret: WEBHOOK_URL
    method: POST
