name: Schedule - Build Container image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**"
      - "!.github/**"
      - ".github/workflows/schedule-docker-build-push.yaml"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-image:
    name: Build Container image
    uses: zaggash/gh-workflows/.github/workflows/run-docker-build-push-semver.yaml@main
    with:
      dockerhub-account: "zaggash"
      github-account: "zaggash"
      image-name: "arch-makepkg"
      context: "./"
      dockerfile: "./Dockerfile"
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      gh_username: ${{ secrets.GH_USERNAME }}
      gh_token: ${{ secrets.PACKAGES_TOKEN }}
